from dataclasses import dataclass
from datetime import datetime
from typing import Optional

@dataclass
class RawFireDepartmentModel:
    incident_number: Optional[int]
    exposure_number: Optional[int]
    id: Optional[int]
    address: Optional[str]
    incident_date: Optional[datetime]
    call_number: Optional[int]
    alarm_dttm: Optional[datetime]
    arrival_dttm: Optional[datetime]
    close_dttm: Optional[datetime]
    city: Optional[str]
    zipcode: Optional[str]
    battalion: Optional[str]
    station_area: Optional[int]
    box: Optional[str]
    suppression_units: Optional[int]
    suppression_personnel: Optional[int]
    ems_units: Optional[int]
    ems_personnel: Optional[int]
    other_units: Optional[int]
    other_personnel: Optional[int]
    first_unit_on_scene: Optional[str]
    estimated_property_loss: Optional[float]
    estimated_contents_loss: Optional[float]
    fire_fatalities: Optional[int]
    fire_injuries: Optional[int]
    civilian_fatalities: Optional[int]
    civilian_injuries: Optional[int]
    number_of_alarms: Optional[int]
    primary_situation: Optional[str]
    mutual_aid: Optional[str]
    action_taken_primary: Optional[str]
    action_taken_secondary: Optional[str]
    action_taken_other: Optional[str]
    detector_alerted_occupants: Optional[str]
    property_use: Optional[str]
    area_of_fire_origin: Optional[str]
    ignition_cause: Optional[str]
    ignition_factor_primary: Optional[str]
    ignition_factor_secondary: Optional[str]
    heat_source: Optional[str]
    item_first_ignited: Optional[str]
    human_factors_associated_with_ignition: Optional[str]
    structure_type: Optional[str]
    structure_status: Optional[str]
    floor_of_fire_origin: Optional[str]
    fire_spread: Optional[str]
    no_flame_spead: Optional[str]
    number_of_floors_with_minimum_damage: Optional[int]
    number_of_floors_with_significant_damage: Optional[int]
    number_of_floors_with_heavy_damage: Optional[int]
    number_of_floors_with_extreme_damage: Optional[int]
    detectors_present: Optional[str]
    detector_type: Optional[str]
    detector_operation: Optional[str]
    detector_effectiveness: Optional[str]
    detector_failure_reason: Optional[str]
    automatic_extinguishing_system_present: Optional[str]
    automatic_extinguishing_sytem_type: Optional[str]
    automatic_extinguishing_sytem_perfomance: Optional[str]
    automatic_extinguishing_sytem_failure_reason: Optional[str]
    number_of_sprinkler_heads_operating: Optional[int]
    supervisor_district: Optional[int]
    neighborhood_district: Optional[str]
    point: Optional[str]

@dataclass
class RawDistrictModel:
    neighborhood_district: Optional[str]
    city: Optional[str]

@dataclass
class RawBattalionModel:
    battalion: Optional[str]